// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe0qx3EOBRzS6FVC98cbYDedh3kWgk-Zo',
    appId: '1:997107121050:web:4ede9edfdab5546fb01823',
    messagingSenderId: '997107121050',
    projectId: 'goodtouchstaff',
    authDomain: 'goodtouchstaff.firebaseapp.com',
    storageBucket: 'goodtouchstaff.appspot.com',
    measurementId: 'G-FWPY0WV52W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq6QqnY1lY6xbROoD6M1k-_X3L3EYyZx8',
    appId: '1:997107121050:android:506262fcd703238db01823',
    messagingSenderId: '997107121050',
    projectId: 'goodtouchstaff',
    storageBucket: 'goodtouchstaff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Ypw-ZUeq53u4qGMU-5qOhjvrRNTzoQk',
    appId: '1:997107121050:ios:ffd188b956d27feab01823',
    messagingSenderId: '997107121050',
    projectId: 'goodtouchstaff',
    storageBucket: 'goodtouchstaff.appspot.com',
    iosClientId: '997107121050-5re1bpbajqtn347dtpd3f6cmj1oo44ac.apps.googleusercontent.com',
    iosBundleId: 'com.bettertouchingstaff.betterTouchingStaff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Ypw-ZUeq53u4qGMU-5qOhjvrRNTzoQk',
    appId: '1:997107121050:ios:ffd188b956d27feab01823',
    messagingSenderId: '997107121050',
    projectId: 'goodtouchstaff',
    storageBucket: 'goodtouchstaff.appspot.com',
    iosClientId: '997107121050-5re1bpbajqtn347dtpd3f6cmj1oo44ac.apps.googleusercontent.com',
    iosBundleId: 'com.bettertouchingstaff.betterTouchingStaff',
  );
}
